import { LegalLayout, LegalSection, legalProse, legalLi } from './LegalLayout';

export function AccessibilityPage() {
  return (
    <LegalLayout
      eyebrow="Accessibility"
      title="Accessibility Statement"
      lastUpdated="August 2026"
      intro={
        <>
          Tekivex is committed to making <strong>tekivex.com</strong> and its free
          in-browser tools usable by everyone — including people who rely on
          keyboards, screen readers, and other assistive technologies.
        </>
      }
    >
      <LegalSection title="Target standard">
        <p style={legalProse}>
          We aim to meet <strong>WCAG 2.2 Level AA</strong> across the website: its
          pages, navigation, legal documents, and the free PDF and CSV tools. This is
          an ongoing target rather than a completed certification — some areas already
          conform, and others are still being improved and tested.
        </p>
      </LegalSection>

      <LegalSection title="What is in place">
        <ul>
          <li style={legalLi}>
            Every page is server-prerendered, so content, headings, navigation, and the
            footer are available without waiting for JavaScript to load.
          </li>
          <li style={legalLi}>
            One <code>&lt;h1&gt;</code> per page and a logical heading order, so
            assistive technology can navigate the page by structure.
          </li>
          <li style={legalLi}>
            A <strong>“Skip to main content”</strong> link as the first focusable
            element on every page, and a visible keyboard focus indicator.
          </li>
          <li style={legalLi}>
            Semantic landmarks (<code>main</code>, <code>nav</code>, <code>footer</code>)
            and descriptive link text.
          </li>
          <li style={legalLi}>
            The PDF and CSV tools use native, labelled file inputs and keyboard-operable
            controls — including button-based reordering, so no action depends on
            drag-and-drop — and announce success and errors to assistive technology
            through live regions.
          </li>
        </ul>
      </LegalSection>

      <LegalSection title="Known limitations">
        <ul>
          <li style={legalLi}>
            The tools have not yet completed a formal third-party accessibility audit.
            We test with keyboards and automated tooling; broader assistive-technology
            testing is ongoing.
          </li>
          <li style={legalLi}>
            Charts generated by the CSV tool are images. When you share one, we recommend
            pairing it with a short text summary or data table — the{' '}
            <a href="/use-cases/how-to-make-chart-from-csv">CSV guide</a> explains how.
          </li>
          <li style={legalLi}>
            Our developer libraries (GridStorm, Tekivex UI) target WCAG 2.1 AA in their
            own documentation; they are separate products with their own accessibility
            status, distinct from this website.
          </li>
        </ul>
      </LegalSection>

      <LegalSection title="Report an accessibility barrier">
        <p style={legalProse}>
          If you encounter a barrier on tekivex.com, please tell us so we can fix it.
          Email{' '}
          <a href="mailto:nishu_singh@tekivex.com">nishu_singh@tekivex.com</a> with the
          page address and what went wrong, or open an issue on our{' '}
          <a
            href="https://github.com/novaai0401-ui/tekivex-issue-report/issues"
            target="_blank"
            rel="noopener noreferrer"
          >
            GitHub issue tracker
          </a>{' '}
          tagged <code>a11y</code>. We aim to respond within a few working days.
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
