// AUTO-GENERATED by scripts/compute-thin-topics.mjs — do not edit by hand.
// Regenerate after adding or substantially editing tutorials:
//   node scripts/compute-thin-topics.mjs

export const THIN_WORD_THRESHOLD = 300;

/**
 * Tutorial pages with fewer than THIN_WORD_THRESHOLD words of prose
 * (code blocks stripped). These pages are:
 *   - marked <meta name="robots" content="noindex,follow">
 *   - excluded from sitemap.xml and feed.xml
 *   - rendered without an AdSlot (to avoid the AdSense "ads on
 *     low-value content" policy hit)
 */
export const THIN_TOPIC_PATHS: ReadonlySet<string> = new Set([
  '/tutorials/ai-ethics/ai-ethics-intro', // 135w
  '/tutorials/ai-ethics/ai-for-business', // 118w
  '/tutorials/ai-ethics/ai-for-individuals', // 126w
  '/tutorials/ai-ethics/chatgpt-ethics', // 106w
  '/tutorials/ai-ethics/core-principles-ethical-ai', // 69w
  '/tutorials/ai-ethics/ethical-ai-deployment', // 64w
  '/tutorials/ai-ethics/ethical-ai-development', // 40w
  '/tutorials/ai-ethics/ethical-data-collection', // 66w
  '/tutorials/ai-ethics/regulatory-frameworks', // 259w
  '/tutorials/ai-langchain/intro-vector-databases', // 91w
  '/tutorials/ai-langchain/langchain-environment', // 3w
  '/tutorials/ai-langchain/langchain-intro', // 91w
  '/tutorials/ai-langchain/langchain-model-inputs', // 4w
  '/tutorials/ai-langchain/langchain-output-parsers', // 24w
  '/tutorials/ai-langchain/langchain-rag', // 84w
  '/tutorials/ai-langchain/langgraph-components', // 6w
  '/tutorials/ai-langchain/langgraph-intro', // 100w
  '/tutorials/ai-langchain/langgraph-message-management', // 28w
  '/tutorials/ai-langchain/langgraph-persistence', // 47w
  '/tutorials/ai-langchain/langgraph-setup', // 2w
  '/tutorials/ai-langchain/lcel', // 23w
  '/tutorials/ai-langchain/pinecone-intro', // 4w
  '/tutorials/ai-langchain/semantic-search-pinecone', // 31w
  '/tutorials/ai-langchain/tokens-models-pricing', // 60w
  '/tutorials/ai-langchain/vector-space', // 74w
  '/tutorials/ai-nlp/fake-news-detection', // 55w
  '/tutorials/ai-nlp/future-of-nlp', // 109w
  '/tutorials/ai-nlp/gpt-models', // 88w
  '/tutorials/ai-nlp/huggingface-transformers', // 30w
  '/tutorials/ai-nlp/intro-llms', // 185w
  '/tutorials/ai-nlp/intro-to-nlp', // 235w
  '/tutorials/ai-nlp/pos-ner', // 87w
  '/tutorials/ai-nlp/qa-with-bert', // 63w
  '/tutorials/ai-nlp/sentiment-analysis', // 46w
  '/tutorials/ai-nlp/text-classifier', // 34w
  '/tutorials/ai-nlp/text-preprocessing', // 69w
  '/tutorials/ai-nlp/topic-modelling', // 37w
  '/tutorials/ai-nlp/transformer-deep-dive', // 61w
  '/tutorials/ai-nlp/vectorizing-text', // 60w
  '/tutorials/ai-nlp/xlnet-text-classification', // 52w
  '/tutorials/ai-speech/analog-to-digital', // 74w
  '/tutorials/ai-speech/asr-environment-setup', // 5w
  '/tutorials/ai-speech/asr-technology-mechanics', // 68w
  '/tutorials/ai-speech/audio-feature-extraction', // 46w
  '/tutorials/ai-speech/llm-engineering-intro', // 101w
  '/tutorials/ai-speech/llm-prototype-development', // 3w
  '/tutorials/ai-speech/noise-spectrograms', // 2w
  '/tutorials/ai-speech/openai-whisper', // 51w
  '/tutorials/ai-speech/planning-stage', // 89w
  '/tutorials/ai-speech/prompt-engineering', // 66w
  '/tutorials/ai-speech/real-world-ai-challenges', // 102w
  '/tutorials/ai-speech/sound-speech-basics', // 114w
  '/tutorials/ai-speech/speech-recognition-intro', // 107w
  '/tutorials/ai-speech/streamlit-llm', // 5w
  '/tutorials/ai-speech/voice-assistant-final', // 29w
  '/tutorials/ai-speech/web-speech-api', // 2w
  '/tutorials/backend-patterns/active-record-vs-data-mapper', // 245w
  '/tutorials/backend-patterns/api-versioning', // 234w
  '/tutorials/backend-patterns/dependency-injection', // 190w
  '/tutorials/backend-patterns/error-handling-patterns', // 202w
  '/tutorials/backend-patterns/logging-observability', // 260w
  '/tutorials/backend-patterns/middleware-pipeline', // 177w
  '/tutorials/backend-patterns/repository-pattern', // 207w
  '/tutorials/backend-patterns/service-layer', // 207w
  '/tutorials/backend-patterns/unit-of-work', // 177w
  '/tutorials/frontend-patterns/compound-components', // 231w
  '/tutorials/frontend-patterns/custom-hooks', // 199w
  '/tutorials/frontend-patterns/higher-order-components', // 269w
  '/tutorials/frontend-patterns/performance-optimization', // 284w
  '/tutorials/frontend-patterns/render-props', // 250w
  '/tutorials/frontend-patterns/state-management', // 266w
  '/tutorials/frontend-patterns/testing-strategies', // 292w
  '/tutorials/software-architecture/clean-architecture', // 197w
  '/tutorials/software-architecture/dependency-inversion', // 193w
  '/tutorials/software-architecture/event-sourcing', // 253w
  '/tutorials/software-architecture/hexagonal-architecture', // 190w
  '/tutorials/software-architecture/interface-segregation', // 166w
  '/tutorials/software-architecture/liskov-substitution', // 161w
  '/tutorials/software-architecture/mvc-pattern', // 227w
  '/tutorials/software-architecture/mvp-pattern', // 226w
  '/tutorials/software-architecture/mvvm-pattern', // 215w
  '/tutorials/software-architecture/open-closed', // 193w
  '/tutorials/software-architecture/single-responsibility', // 253w
  '/tutorials/system-design/authentication-and-authorization', // 189w
  '/tutorials/system-design/availability-reliability', // 191w
  '/tutorials/system-design/backup-and-recovery-strategies', // 198w
  '/tutorials/system-design/big-data-fundamentals', // 241w
  '/tutorials/system-design/caching-for-speed-optimization', // 102w
  '/tutorials/system-design/concurrency-and-parallelism', // 153w
  '/tutorials/system-design/cors-cross-origin-resource-sharing', // 274w
  '/tutorials/system-design/data-protection-and-secure-communication', // 147w
  '/tutorials/system-design/database-models-sql-vs-nosql', // 226w
  '/tutorials/system-design/database-performance-optimization', // 181w
  '/tutorials/system-design/design-chat-application', // 67w
  '/tutorials/system-design/design-cloud-storage', // 188w
  '/tutorials/system-design/design-collaborative-document-editor', // 187w
  '/tutorials/system-design/design-ecommerce-platform', // 125w
  '/tutorials/system-design/design-news-feed', // 41w
  '/tutorials/system-design/design-notification-system', // 202w
  '/tutorials/system-design/design-ride-hailing-app', // 112w
  '/tutorials/system-design/design-search-engine', // 161w
  '/tutorials/system-design/design-ticketing-system', // 223w
  '/tutorials/system-design/design-video-sharing-platform', // 158w
  '/tutorials/system-design/disaster-recovery-in-practice', // 66w
  '/tutorials/system-design/file-systems-and-distributed-storage', // 33w
  '/tutorials/system-design/forward-proxy-vs-reverse-proxy', // 259w
  '/tutorials/system-design/four-step-system-design-approach', // 272w
  '/tutorials/system-design/high-availability-fault-tolerance-failover', // 90w
  '/tutorials/system-design/http-backbone-of-the-web', // 299w
  '/tutorials/system-design/introduction-to-system-performance', // 207w
  '/tutorials/system-design/introduction-to-system-reliability', // 129w
  '/tutorials/system-design/messaging-queues-for-decoupling', // 240w
  '/tutorials/system-design/modern-api-protocols', // 295w
  '/tutorials/system-design/network-and-infrastructure-security', // 277w
  '/tutorials/system-design/object-storage-modern-systems', // 153w
  '/tutorials/system-design/real-time-communication-protocols', // 292w
  '/tutorials/system-design/serialization-data-exchange-formats', // 293w
  '/tutorials/system-design/sharding-replication-polyglot', // 70w
  '/tutorials/system-design/storage-in-system-design-cap-theorem', // 279w
  '/tutorials/system-design/web-sessions-managing-state', // 233w
]);

export function isThinTopic(path: string): boolean {
  return THIN_TOPIC_PATHS.has(path);
}
